// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOodontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOodontologicaAPIContext))]
    [Migration("20260925021248_V02")]
    partial class V02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCita"));

                    b.Property<string>("estadoCita")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idConsultorio")
                        .HasColumnType("integer");

                    b.Property<int>("idOdontologo")
                        .HasColumnType("integer");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("idCita");

                    b.HasIndex("idConsultorio");

                    b.HasIndex("idOdontologo");

                    b.HasIndex("idPaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Consultorio", b =>
                {
                    b.Property<int>("idConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsultorio"));

                    b.Property<string>("equipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("numeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("piso")
                        .HasColumnType("integer");

                    b.HasKey("idConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.Property<int>("idDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleCita"));

                    b.Property<decimal>("costoAplicado")
                        .HasColumnType("Decimal(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("idTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("idDetalleCita");

                    b.HasIndex("idCita");

                    b.HasIndex("idTratamiento");

                    b.ToTable("detallescita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("idEspecialidad");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFactura"));

                    b.Property<string>("estadoPago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("impuestos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("subTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric");

                    b.HasKey("idFactura");

                    b.HasIndex("idCita");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.Property<int>("idHistorialMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorialMedico"));

                    b.Property<string>("alergias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("enfermedadesPrevias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("tipoSangre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("idHistorialMedico");

                    b.HasIndex("idPaciente");

                    b.ToTable("historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.Property<int>("idOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOdontologo"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("registroMedico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registro_medico");

                    b.HasKey("idOdontologo");

                    b.HasIndex("idEspecialidad");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("idPaciente");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.Property<int>("idReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReceta"));

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("indicaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idReceta");

                    b.HasIndex("idCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Tratamiento", b =>
                {
                    b.Property<int>("idTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTratamiento"));

                    b.Property<decimal>("costoBase")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_base");

                    b.Property<TimeOnly>("duracionEstimadaMinutos")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("idTratamiento");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Consultorio", "consultorio")
                        .WithMany()
                        .HasForeignKey("idConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Odontologo", "odontologo")
                        .WithMany()
                        .HasForeignKey("idOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("consultorio");

                    b.Navigation("odontologo");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Tratamiento", "tratamiento")
                        .WithMany()
                        .HasForeignKey("idTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");

                    b.Navigation("tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Especialidad", "especialidad")
                        .WithMany()
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Cita", "cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cita");
                });
#pragma warning restore 612, 618
        }
    }
}
